/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.view;

import Domain.Izvodjac;
import Domain.Kompozicija;
import Domain.Korisnik;
import Domain.Partitura;
import Domain.ZvucniZapis;
import UI.view.components.TableModelSearchKompozicja;
import UI.view.components.TableModelZvucniZapis;
import UI.view.components.TableModelKorisnik;
import UI.view.components.TableModelPartitura;
import communication.CommunicationController;
import Domain.OpstiDomenskiObjekat;
import java.io.IOException;
import java.util.ArrayList;
import java.util.GregorianCalendar;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Leon
 */
public class KompozicijaFrame extends javax.swing.JFrame {

    private Korisnik selektovaniKorisnik;

    /**
     * Creates new form KompozicijaFrame
     */
    public KompozicijaFrame() {
        initComponents();
        prepareview();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        KorisniciTable = new javax.swing.JTable();
        SearchUsersTextField = new javax.swing.JTextField();
        searchUsersButton = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        saveKompozicijajButton = new javax.swing.JButton();
        nazivKompozicijeTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        PartiturejTable = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        putDoFajlaPartituraTextField = new javax.swing.JTextField();
        formatPartituraTextField = new javax.swing.JTextField();
        valutaPartituraTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cenaPartituraTextField = new javax.swing.JTextField();
        dodajPartituruButton = new javax.swing.JButton();
        putDoFajlaZvucniZapisjTextField = new javax.swing.JTextField();
        formatZvucniZapisTextField = new javax.swing.JTextField();
        cenaZvucniZapisjTextField = new javax.swing.JTextField();
        valutaZvucniZapisjTextField = new javax.swing.JTextField();
        izvodjacZvucniZapisjTextField = new javax.swing.JTextField();
        duzinaZvucniZapisTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        ZvucniZapisjTable = new javax.swing.JTable();
        dodajZvucniZapisButton = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        SearchKopozicijajTable = new javax.swing.JTable();
        searchKompozicijaTextField = new javax.swing.JTextField();
        searchKompozicijaButton = new javax.swing.JButton();
        obrisiZvucniZapisJButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        KorisniciTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6"
            }
        ));
        KorisniciTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                KorisniciTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(KorisniciTable);

        searchUsersButton.setText("Pretrazi Korisnike");
        searchUsersButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchUsersButtonActionPerformed(evt);
            }
        });

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(204, 204, 204));

        jTextField2.setEditable(false);
        jTextField2.setBackground(new java.awt.Color(204, 204, 204));

        jTextField3.setEditable(false);
        jTextField3.setBackground(new java.awt.Color(204, 204, 204));

        jTextField4.setEditable(false);
        jTextField4.setBackground(new java.awt.Color(204, 204, 204));

        jTextField5.setEditable(false);
        jTextField5.setBackground(new java.awt.Color(204, 204, 204));

        jTextField6.setEditable(false);
        jTextField6.setBackground(new java.awt.Color(204, 204, 204));

        saveKompozicijajButton.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        saveKompozicijajButton.setText("Sacuvaj Kompoziciju");
        saveKompozicijajButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveKompozicijajButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Naziv Kompozicije");

        jLabel2.setText("Izaberite Kompozitora");

        PartiturejTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(PartiturejTable);

        jLabel3.setText("Unesite Partiture");

        jLabel4.setText("Put do fajla");

        jLabel5.setText("Format");

        jLabel6.setText("Cena");

        jLabel7.setText("Valuta");

        dodajPartituruButton.setText("Dodaj Partituru");
        dodajPartituruButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dodajPartituruButtonActionPerformed(evt);
            }
        });

        jLabel8.setText("Duzina");

        jLabel9.setText("Put do fajla");

        jLabel10.setText("Format");

        jLabel11.setText("Cena");

        jLabel12.setText("Valuta");

        jLabel13.setText("Izvodjac");

        ZvucniZapisjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6"
            }
        ));
        jScrollPane3.setViewportView(ZvucniZapisjTable);

        dodajZvucniZapisButton.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        dodajZvucniZapisButton.setText("Dodaj Zvucni Zapis");
        dodajZvucniZapisButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dodajZvucniZapisButtonActionPerformed(evt);
            }
        });

        SearchKopozicijajTable.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        SearchKopozicijajTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        SearchKopozicijajTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SearchKopozicijajTableMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(SearchKopozicijajTable);

        searchKompozicijaButton.setText("Pretrazi Kompozicije");
        searchKompozicijaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchKompozicijaButtonActionPerformed(evt);
            }
        });

        obrisiZvucniZapisJButton.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        obrisiZvucniZapisJButton.setText("Obrisi Zvucni Zapis");
        obrisiZvucniZapisJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                obrisiZvucniZapisJButtonActionPerformed(evt);
            }
        });

        jButton1.setText("Obrisi Partituru");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel14.setText("Unesite Zvucne Zapise");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(searchKompozicijaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(searchKompozicijaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 301, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(valutaZvucniZapisjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(izvodjacZvucniZapisjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cenaZvucniZapisjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(formatZvucniZapisTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(putDoFajlaZvucniZapisjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(duzinaZvucniZapisTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(saveKompozicijajButton, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(nazivKompozicijeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel11)
                                            .addComponent(jLabel10)
                                            .addComponent(jLabel12)
                                            .addComponent(jLabel13))
                                        .addGap(438, 438, 438))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(300, 300, 300)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(cenaPartituraTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(formatPartituraTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(valutaPartituraTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(dodajPartituruButton, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel7)
                                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(putDoFajlaPartituraTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(dodajZvucniZapisButton, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(obrisiZvucniZapisJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(22, 22, 22)
                                        .addComponent(SearchUsersTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(searchUsersButton, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 622, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(36, 36, 36)
                                        .addComponent(jLabel3))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel14)))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(nazivKompozicijeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(saveKompozicijajButton, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel14)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(duzinaZvucniZapisTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(putDoFajlaZvucniZapisjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(formatZvucniZapisTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cenaZvucniZapisjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(valutaZvucniZapisjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(izvodjacZvucniZapisjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(obrisiZvucniZapisJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dodajZvucniZapisButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(putDoFajlaPartituraTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(searchKompozicijaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(searchKompozicijaButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(formatPartituraTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cenaPartituraTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6))
                                .addGap(7, 7, 7)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(valutaPartituraTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(dodajPartituruButton)
                                    .addComponent(jButton1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(62, 62, 62)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(SearchUsersTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(searchUsersButton)))
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void KorisniciTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KorisniciTableMouseClicked
        int selectedRow = KorisniciTable.getSelectedRow();
        if (selectedRow != -1) {
            TableModelKorisnik model = (TableModelKorisnik) KorisniciTable.getModel();
            Korisnik k = model.getKorisnikAt(selectedRow);
            selektovaniKorisnik = k;
            jTextField1.setText(k.getID());
            jTextField2.setText(k.getIme());
            jTextField3.setText(k.getPrezime());
            jTextField4.setText(k.getClanOd().get(GregorianCalendar.DAY_OF_MONTH) + "-" + k.getClanOd().get(GregorianCalendar.MONTH) + "-" + k.getClanOd().get(GregorianCalendar.YEAR));
            jTextField5.setText(k.getUsername());
            jTextField6.setText(k.getEmail());
        }
    }//GEN-LAST:event_KorisniciTableMouseClicked

    private void searchUsersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchUsersButtonActionPerformed
        SearchUsers();
    }//GEN-LAST:event_searchUsersButtonActionPerformed

    private void saveKompozicijajButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveKompozicijajButtonActionPerformed
        if (selektovaniKorisnik != null) {
            try {
                Kompozicija kompozicija = new Kompozicija();
                kompozicija.setNaziv(nazivKompozicijeTextField.getText());
                kompozicija.setKorisnikID(selektovaniKorisnik);
                GregorianCalendar datum = new GregorianCalendar();
                kompozicija.setUbaziOd(datum);

                TableModelZvucniZapis modelZvucniZapis = (TableModelZvucniZapis) ZvucniZapisjTable.getModel();
                TableModelPartitura modelPartitura = (TableModelPartitura) PartiturejTable.getModel();

                CommunicationController.getInstance().saveKompozicija(kompozicija, modelPartitura.getAllPartiture(), modelZvucniZapis.getAllZvucniZapis(), modelZvucniZapis.getAllIzvodjac());
                JOptionPane.showMessageDialog(this, "Sistem je sacuvao kompoziciju", "Obavestenje", JOptionPane.INFORMATION_MESSAGE);
            } catch (Exception ex) {
                Logger.getLogger(KompozicijaFrame.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this, ex.getMessage(), "Greska", JOptionPane.ERROR_MESSAGE);
            }

        } else {
            JOptionPane.showMessageDialog(this, "Izaberite Kompozitora", "Obavestenje", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_saveKompozicijajButtonActionPerformed

    private void dodajPartituruButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dodajPartituruButtonActionPerformed

        try {
            validacijaPartitura();

            Partitura p = new Partitura();
            p.setPutDoFajla(putDoFajlaPartituraTextField.getText().replace("\\", "\\\\"));
            p.setCena(Double.valueOf(cenaPartituraTextField.getText()));
            p.setValuta(valutaPartituraTextField.getText());
            p.setFormat(formatPartituraTextField.getText());
            TableModelPartitura model = (TableModelPartitura) PartiturejTable.getModel();

            model.addPartitura(p);
            model.fireTableDataChanged();
        } catch (NumberFormatException ex) {
            Logger.getLogger(KompozicijaFrame.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Cena mora biti broj: " + ex.getMessage(), "Paznja", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception ex) {
            Logger.getLogger(KompozicijaFrame.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_dodajPartituruButtonActionPerformed

    private void dodajZvucniZapisButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dodajZvucniZapisButtonActionPerformed
        ZvucniZapis z = new ZvucniZapis();
        Izvodjac i = new Izvodjac();

        try {
            validacijaZvucniZapis();

            z.setDuzina(Integer.valueOf(duzinaZvucniZapisTextField.getText()));
            z.setCena(Double.valueOf(cenaZvucniZapisjTextField.getText()));
            z.setFormat(formatZvucniZapisTextField.getText());
            z.setPutDoFajla(putDoFajlaZvucniZapisjTextField.getText().replace("\\", "\\\\"));
            z.setValuta(valutaZvucniZapisjTextField.getText());
            i.setNaziv(izvodjacZvucniZapisjTextField.getText());

            TableModelZvucniZapis model = (TableModelZvucniZapis) ZvucniZapisjTable.getModel();
            model.addZvucniZapisSaIzvodjacem(z, i);
            model.fireTableDataChanged();

        } catch (NumberFormatException ex) {
            Logger.getLogger(KompozicijaFrame.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Duzina mora biti ceo broj, Cena mora biti broj: " + ex.getMessage(), "Paznja", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception ex) {
            Logger.getLogger(KompozicijaFrame.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Paznja", JOptionPane.INFORMATION_MESSAGE);
        }


    }//GEN-LAST:event_dodajZvucniZapisButtonActionPerformed

    private void searchKompozicijaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchKompozicijaButtonActionPerformed
        try {

            List<OpstiDomenskiObjekat> ListaODO = CommunicationController.getInstance().searchKompozicija(new Kompozicija(), searchKompozicijaTextField.getText());
            List<Kompozicija> kompozicije = new ArrayList<>();
            List<Partitura> partiture = new ArrayList<>();
            List<ZvucniZapis> zvucniZapisi = new ArrayList<>();
            List<Izvodjac> izvodjaci = new ArrayList<>();
            List<Korisnik> korisnikci = new ArrayList<>();

            for (int i = 0; i < ListaODO.size(); i = i + 5) {
                kompozicije.add((Kompozicija) ListaODO.get(i));
                partiture.add((Partitura) ListaODO.get(i + 1));
                zvucniZapisi.add((ZvucniZapis) ListaODO.get(i + 2));
                izvodjaci.add((Izvodjac) ListaODO.get(i + 3));
                korisnikci.add((Korisnik) ListaODO.get(i + 4));
            }

            TableModelSearchKompozicja model = new TableModelSearchKompozicja(kompozicije, partiture, zvucniZapisi, izvodjaci, korisnikci);
            model.fireTableStructureChanged();
            SearchKopozicijajTable.setModel(model);
            SearchKopozicijajTable.getColumnModel().getColumn(4).setPreferredWidth(28);

        } catch (Exception ex) {
            Logger.getLogger(KompozicijaFrame.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Greska pri pretrazivanju kompozicija", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_searchKompozicijaButtonActionPerformed

    private void SearchKopozicijajTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchKopozicijajTableMouseClicked
        int selectedRow = SearchKopozicijajTable.getSelectedRow();
        if (selectedRow != -1) {
            TableModelSearchKompozicja model = (TableModelSearchKompozicja) SearchKopozicijajTable.getModel();
            List<OpstiDomenskiObjekat> listaODO = model.getKopozicijaDataAt(selectedRow);
            try {
                CommunicationController.getInstance().setSavedData(listaODO);
            } catch (IOException ex) {
                Logger.getLogger(UserFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
            JPanel pannel = new KompozicijaDetailsPanel();
            JDialog dialog = new JDialog(this, "Detalji o kompoziciji", true);
            dialog.add(pannel);
            //   dialog.setLocationRelativeTo(this);
            dialog.setLocation(150, 150);
            dialog.pack();
            dialog.setVisible(true);
        }
    }//GEN-LAST:event_SearchKopozicijajTableMouseClicked

    private void obrisiZvucniZapisJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_obrisiZvucniZapisJButtonActionPerformed
        TableModelZvucniZapis model = (TableModelZvucniZapis) ZvucniZapisjTable.getModel();
        model.removeLastZvucniZapis();
        model.fireTableDataChanged();
    }//GEN-LAST:event_obrisiZvucniZapisJButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        TableModelPartitura model = (TableModelPartitura) PartiturejTable.getModel();
        model.removeLastPartitura();
        model.fireTableDataChanged();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void SearchUsers() {
        Korisnik k = new Korisnik();
        List<Korisnik> listaKorisnika = new ArrayList<>();

        try {
            listaKorisnika = CommunicationController.getInstance().searchKorisnik(k, SearchUsersTextField.getText());
        } catch (IOException ex) {
            Logger.getLogger(UserFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(UserFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        TableModelKorisnik model = new TableModelKorisnik(listaKorisnika);
        KorisniciTable.setModel(model);

    }

    private void validacijaZvucniZapis() throws Exception {
        if (formatZvucniZapisTextField.getText().equals("") || putDoFajlaZvucniZapisjTextField.getText().equals("") || cenaZvucniZapisjTextField.getText().equals("") || duzinaZvucniZapisTextField.getText().equals("") || izvodjacZvucniZapisjTextField.getText().equals("") || valutaZvucniZapisjTextField.getText().equals("")) {
            throw new Exception("Sva polja su obavezna");
        }

    }

    private void validacijaPartitura() throws Exception {
        if (putDoFajlaPartituraTextField.getText().equals("") || cenaPartituraTextField.getText().equals("") || valutaPartituraTextField.getText().equals("") || formatPartituraTextField.getText().equals("")) {
            throw new Exception("Sva polja su obavezna");
        }

    }

    private void prepareview() {
        setLocationRelativeTo(null);
        SearchUsers();
        List<Partitura> partiture = new ArrayList<>();
        TableModelPartitura model = new TableModelPartitura(partiture);
        PartiturejTable.setModel(model);
        List<ZvucniZapis> zvucniZapisi = new ArrayList<>();
        List<Izvodjac> izvodjaci = new ArrayList<>();
        TableModelZvucniZapis model2 = new TableModelZvucniZapis(zvucniZapisi, izvodjaci);
        ZvucniZapisjTable.setModel(model2);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KompozicijaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KompozicijaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KompozicijaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);

            {
                java.util.logging.Logger.getLogger(KompozicijaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
            //</editor-fold>

            /* Create and display the form */
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    new KompozicijaFrame().setVisible(true);
                }
            });
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(KompozicijaFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable KorisniciTable;
    private javax.swing.JTable PartiturejTable;
    private javax.swing.JTable SearchKopozicijajTable;
    private javax.swing.JTextField SearchUsersTextField;
    private javax.swing.JTable ZvucniZapisjTable;
    private javax.swing.JTextField cenaPartituraTextField;
    private javax.swing.JTextField cenaZvucniZapisjTextField;
    private javax.swing.JButton dodajPartituruButton;
    private javax.swing.JButton dodajZvucniZapisButton;
    private javax.swing.JTextField duzinaZvucniZapisTextField;
    private javax.swing.JTextField formatPartituraTextField;
    private javax.swing.JTextField formatZvucniZapisTextField;
    private javax.swing.JTextField izvodjacZvucniZapisjTextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField nazivKompozicijeTextField;
    private javax.swing.JButton obrisiZvucniZapisJButton;
    private javax.swing.JTextField putDoFajlaPartituraTextField;
    private javax.swing.JTextField putDoFajlaZvucniZapisjTextField;
    private javax.swing.JButton saveKompozicijajButton;
    private javax.swing.JButton searchKompozicijaButton;
    private javax.swing.JTextField searchKompozicijaTextField;
    private javax.swing.JButton searchUsersButton;
    private javax.swing.JTextField valutaPartituraTextField;
    private javax.swing.JTextField valutaZvucniZapisjTextField;
    // End of variables declaration//GEN-END:variables
}
